server:
  port: 7075
spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/HRProjectMailService
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
  mail:
    host: smtp.gmail.com
    port: 587
    username: gizemliankaralilar@gmail.com
    password: nncgzgvysokjibye
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true