server:
  port: 9091

spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/HRCompany
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789

rabbitmqKey:
  auth-exchange: auth-exchange
  register-queue: register-queue
  register-binding-key: binding-key

