server:
  port: 80
  error:
    whitelabel:
      enabled: false

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9400
    service:
      name: api-gateway
  cloud:
    gateway:
#      httpclient:
#        ssl:
#          use-insecure-trust-manager: true
      default-filters:
        #        http://localhost/auth/findById/1
        #        /(?<segment>.*) :auth/findById/1
        #        /$\{segment} : bu kısım yakalanan segmenti uri'ye ekleyecek.
        #        http://localhost:9090/auth/findById/1
        - RewritePath= /(?<segment>.*), /$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: company-service
          uri: http://localhost:9091
          predicates:
            - Path=/company/**
          filters:
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallback/company
        - id: employee-service
          uri: http://localhost:9093
          predicates:
            - Path=/employee/**
          filters:
            - name: CircuitBreaker
              args:
                name: employee
                fallbackUri: forward:/fallback/employee