server.port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
  zipkin:
    enabled: true
    base-url: http://localhost:9400
    service:
      name: sale-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username:  ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/HREmployee
  jpa:
    hibernate:
      ddl-auto: update

authservice:
  secrets:
    key: ${JAVA_SECRETKEY}
    issuer: ${JAVA_ISSUER}
    exDate: 300000
